---
- name: Check if Java is already installed
  command: java -version
  register: java_check
  failed_when: false
  changed_when: false

- name: Install OpenJDK 17
  apt:
    name: openjdk-17-jdk
    state: present
    update_cache: yes
    cache_valid_time: 86400
  when: java_check.rc != 0

- name: Verify Java Installation
  command: java -version
  register: java_version
  changed_when: false

- name: Display Java Version
  debug:
    var: java_version.stderr_lines
