---
#################################################
# SSH Configuration
#################################################

ansible_user: ubuntu

ansible_ssh_private_key_file: ~/.ssh/kafka-key.pem

ansible_ssh_common_args: >-
  -o StrictHostKeyChecking=no
  -o ForwardAgent=yes
  -o ProxyJump=kafka-bastion
#################################################
# Kafka Version
#################################################

kafka_version: "3.7.1"
kafka_scala_version: "2.13"

#################################################
# Kafka Download
#################################################

kafka_download_url: "https://archive.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ kafka_scala_version }}-{{ kafka_version }}.tgz"

#################################################
# Kafka Cluster
#################################################

kafka_cluster_id: "LpJFO8ZTRe6yI4NvteWRkQ"

#################################################
# Kafka Heap
#################################################

kafka_heap_xms: "128M"
kafka_heap_xmx: "256M"

#################################################
# Kafka Directories
#################################################

kafka_install_dir: "/opt/kafka"

kafka_log_dir: "/tmp/kraft-combined-logs"
# Local Kafka artifact cache
kafka_cache_dir: "{{ lookup('env','HOME') }}/.cache/kafka"
