plugin: amazon.aws.aws_ec2

regions:
  - us-east-1

filters:
  instance-state-name: running
  tag:Project: Kafka-Infrastructure-Platform
  tag:Role: kafka

hostnames:
  - tag:Name
  - private-ip-address

compose:
  ansible_host: private_ip_address

keyed_groups:
  - prefix: role
    key: ec2_tags.Role

  - prefix: env
    key: ec2_tags.Environment

  - prefix: cluster
    key: ec2_tags.Cluster

strict: false
